import type { Config } from "tailwindcss";

const config: Config = {
   content: 
    [
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
      "./pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        tablet: "640px",
        laptop: "1000px",
        desktop: "1280px",
      },
      fontFamily: {
        sans: ["ui-sans-serif", "system-ui"],
        serif: ["ui-serif", "Georgia"],
        playwrite: ["Playwrite PE"],
        cursive: ["cursive"],
      },
      backgroundColor: {
        blue: "#0d94c4",
        white: "#ffffff",
        black: "#000000",
        rose: "#ff7882",
        beige: "	#f7c57a",
        somon: "#ffbbaf",
        ciel: "	#96dbdb",
        orange: "#ff9900",
        red: "#c2050b",
        sugar: "#fff5ec",
        yellow: "#ffe79c",
        purple: "#a178a1",
        "light-purple": "#eed6ee",
        pink: "#f7b4d6",
        "light-brown": "#DBA95F",
        brown: "#b08645",
        coral: "#FF7F50",
        "brown-peach": "#d36c6c",

        peach: "#f23c50",
        veraman: "#00ffae",
        green: "#6cc24a",
      },
      borderColor: {
        blue: "#0d94c4",
        white: "#ffffff",
        coral: "#FF7F50",
        black: "#000000",
        rose: "#ff7882",
        beige: "	#f7c57a",
        somon: "#ffbbaf",
        ciel: "	#96dbdb",
        orange: "#ff9900",
        red: "#c2050b",
        sugar: "#fff5ec",
        yellow: "#ffe79c",
        purple: "#a178a1",
        "light-purple": "#eed6ee",
        pink: "#f7b4d6",
        "light-brown": "#DBA95F",
        brown: "#b08645",
        peach: "#f23c50",
        veraman: "#00ffae",
        green: "#6cc24a",
        "brown-peach": "#d36c6c",
      },
      textColor: {
        blue: "#0d94c4",
        white: "#ffffff",
        black: "#000000",
        rose: "#ff7882",
        coral: "#FF7F50",
        "brown-peach": "#d36c6c",

        beige: "	#f7c57a",
        somon: "#ffbbaf",
        ciel: "	#96dbdb",
        orange: "#ff9900",
        red: "#c2050b",
        sugar: "#fff5ec",
        yellow: "#ffe79c",
        purple: "#a178a1",
        "light-purple": "#eed6ee",
        pink: "#f7b4d6",
        "light-brown": "#DBA95F",
        brown: "#b08645",
        peach: "#f23c50",
        veraman: "#00ffae",
        green: "#6cc24a",
      },
    },
  },
  plugins: [],
};
export default config;
